const CardPool = {
  cards: {
    items: [
      { name: 'Edoardo Biagioni',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/edoardo-biagioni-1.png',
        desc: 'Description here',
        rarity: 1,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 211, ICS 491',
        index: 0 },
      { name: 'Kenny Quibilan',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/kenny-quibilan-1.png',
        desc: 'Description here',
        rarity: 1,
        title: 'ICS Academic Advisor',
        classes: 'Tutors: ICS Lower Division',
        index: 1 },
      { name: 'Peter Seidel',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/peter-seidel-1.png',
        desc: 'Description here',
        rarity: 1,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 331, ICS 355',
        index: 2 },
      { name: 'Scott Robertson',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/scott-robertson-1.png',
        desc: 'Description here',
        rarity: 1,
        title: 'ICS Professor & Chair',
        classes: 'Taught: ICS 111, ICS 211',
        index: 3 },
      { name: 'Depeng Li',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/depeng-li-2.png',
        desc: 'Description here',
        rarity: 2,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 141, ICS 241',
        index: 4 },
      { name: 'Dan Suthers',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/dan-suthers-2.png',
        desc: 'Description here',
        rarity: 2,
        title: 'ICS Professor & Chair',
        classes: 'Teaches: ICS 311, ICS 400+',
        index: 5 },
      { name: 'Guylaine Poisson',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/guylaine-poisson-2.png',
        desc: 'Description here',
        rarity: 2,
        title: 'ICS Professor & Chair',
        classes: 'Taught: ICS 110, ICS 290',
        index: 6 },
      { name: 'Nodari Sitchinava',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/nodari-sitchinava-2.png',
        desc: 'Description here',
        rarity: 2,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 311, ICS 400+',
        index: 7 },
      { name: 'Carleton Moore',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/carleton-moore-3.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 111, ICS 314',
        index: 8 },
      { name: 'Henri Casanova',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/henri-casanova-3.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Professor',
        classes: 'Taught: ICS 312, ICS 332',
        index: 9 },
      { name: 'Ravi Narayan',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/ravi-narayan-3.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Instructor',
        classes: 'Teaches: ICS 212, ICS 332',
        index: 10 },
      { name: 'Philip Johnson',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/philip-johnson-3.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Professor',
        classes: 'Teaches: ICS 314, ICS 100+',
        index: 11 },
      { name: 'Chad Morita',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1713779203/demo4_ztqtqw.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Lecturer',
        classes: 'Teaches: ICS 314, ICS 332',
        index: 12 },
      { name: 'Edoardo Biagioni',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/edoardo-biagioni-4.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 211, ICS 491',
        index: 13 },
      { name: 'Kim Binsted',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1713779203/demo4_ztqtqw.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Professor',
        classes: 'Taught: ICS 361, ICS 461',
        index: 14 },
      { name: 'Scott Robertson',
        image: 'https://raw.githubusercontent.com/ProfTCG/proftcg/main/app/public/images/Card-Images/scott-robertson-4.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Professor & Chair',
        classes: 'Taught: ICS 111, ICS 211',
        index: 15 },
    ],
  },
};

export default CardPool;
