const CardPool = {
  cards: {
    items: [
      { name: 'Edoardo Biagioni',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1715051493/Cards/edoedo2_n5jlwe.png',
        desc: 'In 2011, Edoardo (or Edo) began his work on AllNet, a project with an end goal of allowing personal devices to communicate directly with each other; in other words, a decentralized network.',
        rarity: 1,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 211, ICS 491',
        index: 0 },
      { name: 'Kenny Quibilan',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714196891/Cards/kenny-q-final_kwmkgg.png',
        desc: 'Kenny Quibilan is a member of the College of Natural Sciences Student Academic Success Center, meaning you can schedule an appointment to meet with him directly. You can find him on the STAR GPS system or in the UH Learning Emporium.',
        rarity: 1,
        title: 'ICS Academic Advisor',
        classes: 'Tutors: ICS Lower Division',
        index: 1 },
      { name: 'Peter Seidel',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714967950/Cards/notherone_uw4g22.png',
        desc: 'Peter-Michael Seidel received his Bachelor of Sciences degree as well as his Master of Sciences degree in Computer Science from the University of Hagen, Germany.',
        rarity: 1,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 331, ICS 355',
        index: 2 },
      { name: 'Scott Robertson',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714192221/Cards/scott-robertson-1_uyimdy.png',
        desc: 'Scott Robertson received his PhD in Psychology from Yale University, specializing in Cognitive Science. His interest lies in all facets of interaction, be it of flesh or machine.',
        rarity: 1,
        title: 'ICS Professor & Chair',
        classes: 'Taught: ICS 111, ICS 211',
        index: 3 },
      { name: 'Depeng Li',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714716529/Cards/DEPENG2_33331_f6ytoy.png',
        desc: 'With a BS and a Master\'s degree from Shandong University, Depeng Li would go on to assist in the development of Windows 7. Throughout the years, he\'s been involved in numerous research talks in the US, Canada, and Asia.',
        rarity: 2,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 141, ICS 241',
        index: 4 },
      { name: 'Dan Suthers',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714639513/Cards/danz_uhindb.png',
        desc: 'With a knack for user interfaces, Dan Suthers has taken a part in countless publications regarding the cognitive, social, and computational perspectives on designing software for learning, collaboration, and community.',
        rarity: 2,
        title: 'ICS Professor & Chair',
        classes: 'Teaches: ICS 311, ICS 400+',
        index: 5 },
      { name: 'Guylaine Poisson',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1715076781/Cards/guylaine_ipw9b2.png',
        desc: 'Teaching Bioinformatics in the ICS department, Guylaine Poisson hails from Montreal, Canada, with ties to the development of analytical and executive methods regarding large-scale genomics projects.',
        rarity: 2,
        title: 'ICS Professor & Chair',
        classes: 'Taught: ICS 110, ICS 290',
        index: 6 },
      { name: 'Nodari Sitchinava',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1713816478/Cards/nodari-sitchinava_iasgqu.png',
        desc: 'Nodari Sitchinava specializes in algorithms for modern parallel systems. ',
        rarity: 2,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 311, ICS 400+',
        index: 7 },
      { name: 'Carleton Moore',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1712760246/Cards/carleton-moore-3S_pd0jft.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 111, ICS 314',
        index: 8 },
      { name: 'Henri Casanova',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714630619/Cards/casanovah_bxjy2p.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Professor',
        classes: 'Taught: ICS 312, ICS 332',
        index: 9 },
      { name: 'Ravi Narayan',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714198162/Cards/ravi-narayan-new_glvdjh.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Instructor',
        classes: 'Teaches: ICS 212, ICS 332',
        index: 10 },
      { name: 'Philip Johnson',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714467448/Cards/doc-philip_szvevi.png',
        desc: 'Description here',
        rarity: 3,
        title: 'ICS Professor',
        classes: 'Teaches: ICS 314, ICS 100+',
        index: 11 },
      /*{ name: 'Chad Morita',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1713779203/demo4_ztqtqw.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Lecturer',
        classes: 'Teaches: ICS 314, ICS 332',
        index: 12 }, */
      { name: 'Edoardo Biagioni',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1712771482/Cards/edoardo-biagioni-4_jhzbip.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Associate Professor',
        classes: 'Teaches: ICS 211, ICS 491',
        index: 12 },
      /* { name: 'Kim Binsted',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1713779203/demo4_ztqtqw.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Professor',
        classes: 'Taught: ICS 361, ICS 461',
        index: 14 }, */
      { name: 'Scott Robertson',
        image: 'https://res.cloudinary.com/dxiainweb/image/upload/v1714239643/Cards/scott-robertson-4-final_eh0wtm.png',
        desc: 'Description here',
        rarity: 4,
        title: 'ICS Professor & Chair',
        classes: 'Taught: ICS 111, ICS 211',
        index: 13 },
    ],
  },
};

export default CardPool;
