import React from 'react';

const CardPool = {
  cards: {
    items: [
      { name: '1A',
        card: <img className="card-entries" src="https://tinyurl.com/5n6c3h4e" alt="first-last-#" />,
        image: 'https://tinyurl.com/5n6c3h4e',
        desc: 'Description here',
        rarity: 1,
        index: 0 },
      { name: '1B',
        card: <img className="card-entries" src="https://tinyurl.com/5n6c3h4e" alt="first-last-#" />,
        image: 'https://tinyurl.com/5n6c3h4e',
        desc: 'Description here',
        rarity: 1,
        index: 1 },
      { name: 'Kenny Quibilan',
        card: <img className="card-entries" src="https://tinyurl.com/2384ddmp" alt="kenny-quibilan-1" />,
        image: 'https://tinyurl.com/2384ddmp',
        desc: 'Description here',
        rarity: 1,
        index: 2 },
      { name: 'Scott Robertson',
        card: <img className="card-entries" src="https://tinyurl.com/mr2ute5t" alt="scott-robertson-1" />,
        image: 'https://tinyurl.com/mr2ute5t',
        desc: 'Description here',
        rarity: 1,
        index: 3 },
      { name: '2A',
        card: <img className="card-entries" src="https://tinyurl.com/bd6u4x92" alt="first-last-#" />,
        image: 'https://tinyurl.com/bd6u4x92',
        desc: 'Description here',
        rarity: 2,
        index: 4 },
      { name: '2B',
        card: <img className="card-entries" src="https://tinyurl.com/bd6u4x92" alt="first-last-#" />,
        image: 'https://tinyurl.com/bd6u4x92',
        desc: 'Description here',
        rarity: 2,
        index: 5 },
      { name: 'Nodari Sitchinava',
        card: <img className="card-entries" src="https://tinyurl.com/4vtrd9zu" alt="nodari-sitchinava-2" />,
        image: 'https://tinyurl.com/4vtrd9zu',
        desc: 'Description here',
        rarity: 2,
        index: 6 },
      { name: '2D',
        card: <img className="card-entries" src="https://tinyurl.com/bd6u4x92" alt="first-last-#" />,
        image: 'https://tinyurl.com/bd6u4x92',
        desc: 'Description here',
        rarity: 2,
        index: 7 },
      { name: 'Carleton Moore',
        card: <img className="card-entries" src="https://tinyurl.com/snffkrem" alt="carleton-moore-3" />,
        image: 'https://tinyurl.com/snffkrem',
        desc: 'Description here',
        rarity: 3,
        index: 8 },
      { name: 'Ravi Narayan',
        card: <img className="card-entries" src="https://tinyurl.com/muu5h669" alt="ravi-narayan-3" />,
        image: 'https://tinyurl.com/muu5h669',
        desc: 'Description here',
        rarity: 3,
        index: 9 },
      { name: 'Philip Johnson',
        card: <img className="card-entries" src="https://tinyurl.com/paksv5sy" alt="philip-johnson-3" />,
        image: 'https://tinyurl.com/paksv5sy',
        desc: 'Description here',
        rarity: 3,
        index: 10 },
      { name: '3D',
        card: <img className="card-entries" src="https://tinyurl.com/4nfrr3uf" alt="first-last-#" />,
        image: 'https://tinyurl.com/4nfrr3uf',
        desc: 'Description here',
        rarity: 3,
        index: 11 },
      { name: '4A',
        card: <img className="card-entries" src="https://tinyurl.com/bd95tn5z" alt="first-last-#" />,
        image: 'https://tinyurl.com/bd95tn5z',
        desc: 'Description here',
        rarity: 4,
        index: 12 },
      { name: 'Edoardo Biagioni',
        card: <img className="card-entries" src="https://tinyurl.com/4xmv9ek3" alt="edoardo-biagioni-4" />,
        image: 'https://tinyurl.com/4xmv9ek3',
        desc: 'Description here',
        rarity: 4,
        index: 13 },
      { name: 'Scott Robertson',
        card: <img className="card-entries" src="https://tinyurl.com/yuzd8c7e" alt="scott-robertson-4" />,
        image: 'https://tinyurl.com/yuzd8c7e',
        desc: 'Description here',
        rarity: 4,
        index: 14 },
      { name: '4D',
        card: <img className="card-entries" src="https://tinyurl.com/bd95tn5z" alt="first-last-#" />,
        image: 'https://tinyurl.com/bd95tn5z',
        desc: 'Description here',
        rarity: 4,
        index: 15 },
      { name: '5A',
        card: <img className="card-entries" src="https://tinyurl.com/mun2amyt" alt="first-last-#" />,
        image: 'https://tinyurl.com/mun2amyt',
        desc: 'Description here',
        rarity: 5,
        index: 16 },
      { name: '5B',
        card: <img className="card-entries" src="https://tinyurl.com/mun2amyt" alt="first-last-#" />,
        image: 'https://tinyurl.com/mun2amyt',
        desc: 'Description here',
        rarity: 5,
        index: 17 },
      { name: '5C',
        card: <img className="card-entries" src="https://tinyurl.com/mun2amyt" alt="first-last-#" />,
        image: 'https://tinyurl.com/mun2amyt',
        desc: 'Description here',
        rarity: 5,
        index: 18 },
      { name: '5D',
        card: <img className="card-entries" src="https://tinyurl.com/mun2amyt" alt="first-last-#" />,
        image: 'https://tinyurl.com/mun2amyt',
        desc: 'Description here',
        rarity: 5,
        index: 19 },
    ],
  },
};

export default CardPool;
